using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;
using TicketingSystem.Services;
using TicketingSystem.Models;
using System.Linq;

namespace Tests.ServiceTests
{
    [TestFixture]
    class DataEditorTest
    {
        [Test]
        public void PostEditTest()
        {
            using (var context = new TicketingSystemDBContext())
            {
                JobType j = new JobType();
                j.JobName = "Miscellaneous";

                TicketData td = new TicketData()
                {
                    EntryId = context.TicketData.Where(t => t.TicketWorker.FullName == "Test User").FirstOrDefault().EntryId,
                    TripNum = 111,
                    StageNum = "S01",
                    JobType = j,
                    EntryAuthor = context.Users.Where(u => u.FullName == "Test User").FirstOrDefault(),
                    TicketWorker = context.Users.Where(w => w.FullName == "Test User").FirstOrDefault(),
                    WorkerName = "Test User",
                    StartTime = DateTime.Now,
                    Comments = "Edit generated by DataEditor.PostEdit unit test"
                };

                DataEditor DaEd = new DataEditor();
                Users dbUser = context.Users.Where(u => u.FullName == "Test User").FirstOrDefault();
                Assert.IsTrue(DaEd.PostEditor(td, Auth0APIClient.GetUserData(dbUser.Auth0Uid)));
            }
        }
    }
}
