using NUnit.Framework;
using System.Collections.Generic;
using TicketingSystem.Services;
using TicketingSystem.Models;
using System;
using System.Linq;

namespace Tests.ServiceTests
{
    [TestFixture]
    public class DataEntryTests
    {
        [Test]
        public void PostEntryTest()
        {
            using (var context = new TicketingSystemDBContext())
            {
                JobType j = new JobType();
                j.JobName = "Miscellaneous";
                
                TicketData td = new TicketData()
                {
                    TripNum = 111,
                    StageNum = "S01",
                    JobType = j,
                    EntryAuthor = context.Users.Where(u => u.FullName == "System Admin").FirstOrDefault(),
                    TicketWorker = context.Users.Where(w => w.FullName == "System Admin").FirstOrDefault(),
                    WorkerName = "System Admin",
                    StartTime = DateTime.Now,
                    Comments = "Entry generated by DataEntry.PostEntry unit test"
                };
                DataEntry de = new DataEntry();
                Assert.IsTrue(de.PostEntry(td));
            }

        }

        [Test]
        public void CloseTicketTest()
        {
            using (var context = new TicketingSystemDBContext())
            {
                var td = context.TicketData.FirstOrDefault();
                DataEntry de = new DataEntry();
                Assert.IsTrue(de.CloseTicket(td));
            }

        }
    }
}
