using NUnit.Framework;
using TicketingSystem.Services;
using TicketingSystem.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Tests.ServiceTests
{
    [TestFixture]
    public class TicketDataLoggerTests
    {
        [Test]
        public void LogChangeTest()
        {
            TicketDataLogger tdl = new TicketDataLogger();
            string action = "LogChangeTest", details = "Entry generated by automated unit test";
            using (var context = new TicketingSystemDBContext())
            {
                var data = context.TicketData.FirstOrDefault();
                if (data != null)
                {
                    Assert.IsTrue(tdl.LogChange(action, details, data.EntryId));
                }
                
            }
        }
    }
}