using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;
using TicketingSystem.Controllers;
using TicketingSystem.Models;
using System.Linq;

namespace Tests.ControllerTests
{
    [TestFixture]
    class HomeControllerTests
    {
        HomeController hc;
        public HomeControllerTests()
        {
            hc = new HomeController();
        }
        [Test]
        public void HomePageTest()
        {
            var result = hc.HomePage();
            Assert.IsNotNull(result);
        }

        [Test]
        public void VerifyLoginTest()
        {
            var result = hc.VerifyLogin(new Users());
            Assert.IsNotNull(result);
        }

        [Test]
        public void DataEntryTest()
        {
            var result = hc.DataEntry();
            Assert.IsNotNull(result);
        }

        [Test]
        public void PostEntryTest()
        {
            using (var context = new TicketingSystemDBContext())
            {
                JobType j = new JobType();
                j.JobName = "Miscellaneous";

                TicketData td = new TicketData()
                {
                    TripNum = 111,
                    StageNum = "S01",
                    JobType = j,
                    EntryAuthor = context.Users.Where(u => u.FullName == "System Admin").FirstOrDefault(),
                    TicketWorker = context.Users.Where(w => w.FullName == "System Admin").FirstOrDefault(),
                    WorkerName = "System Admin",
                    StartTime = DateTime.Now,
                    Comments = "Entry generated by HomeController.PostEntry unit test"
                };
                var result = hc.PostEntry(td);
                Assert.IsNotNull(result);
            }

        }
    }
}
