using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;
using TicketingSystem.Controllers;
using TicketingSystem.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Security.Principal;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;

namespace Tests.ControllerTests
{
    [TestFixture]
    class HomeControllerTests : Controller
    {
        HomeController hc;
        public HomeControllerTests()
        {
            hc = new HomeController();
            hc.ControllerContext = new ControllerContext
            {
                HttpContext = new DefaultHttpContext
                {
                    User = new ClaimsPrincipal(new ClaimsIdentity(new Claim[]
                    {
                        new Claim(ClaimTypes.Name, "testUser")
                    }, "testAuthType"))
                }
            };
        }
        [Test]
        public void HomePageTest()
        {
            
            var result = hc.HomePage();
            Assert.IsNotNull(result);
        }

        [Test]
        public void VerifyLoginTest()
        {
            var result = hc.VerifyLogin(new Users());
            Assert.IsNotNull(result);
        }

        [Test]
        public void DataEntryTest()
        {
            var result = hc.DataEntry();
            Assert.IsNotNull(result);
        }

        [Test]
        public void PostEntryTest()
        {
            using (var context = new TicketingSystemDBContext())
            {
                JobType j = new JobType();
                j.JobName = "Miscellaneous";

                TicketData td = new TicketData()
                {
                    TripNum = 111,
                    StageNum = "S01",
                    JobType = j,
                    EntryAuthor = context.Users.Where(u => u.FullName == "System Admin").FirstOrDefault(),
                    TicketWorker = context.Users.Where(w => w.FullName == "System Admin").FirstOrDefault(),
                    WorkerName = "System Admin",
                    StartTime = DateTime.Now,
                    Comments = "Entry generated by HomeController.PostEntry unit test"
                };
                var result = hc.PostEntry(td);
                Assert.IsNotNull(result);
            }

        }
    }

    public class TestPrincipal : ClaimsPrincipal
    {
        public TestPrincipal(params Claim[] claims) : base(new TestIdentity(claims))
        {
        }
    }

    public class TestIdentity : ClaimsIdentity
    {
        public TestIdentity(params Claim[] claims) : base(claims)
        {
        }
    }
}
